name: Release

on:
  push:
    branches:
      - test

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: yarn install

    - name: Semantic Release
      run:  npx semantic-release --branches test
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
